model: "gpt-3.5-turbo" # gpt-4o, gpt-3.5-turbo, gpt-4-turbo
retriever: "hybrid" # qdrant_dense, chroma_dense, sparse, hybrid
text_splitter: "recursive" # sentence, character, semantic, recursive
chunk_size: 900 # chunk_size
chunk_overlap: 50 # chunk_overlap
query_translation: "hyde" # multi_query, rag_fusion, decomposition, hyde, raptor, no_translation